import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Select from "react-select";
import general_book from "../config/general_book";
import magazine_dissertation from "../config/magazine_dissertation";
import translated_book from "../config/translated_book";
import styles from "../styles/Home.module.css";

const format_type = {
  translated_book: translated_book,
  general_book: general_book,
  magazine_dissertation: magazine_dissertation,
};

const GenerateComponent = ({ method }) => {
  const datas = format_type[method].datas;
  const list = Object.keys(datas);
  const [results, setResults] = useState(datas);
  const generatedText = format_type[method].text(results);
  return (
    <>
      {list.map((text) => {
        return (
          <input
            placeholder={datas[text]}
            onChange={(e) => setResults({ ...results, [text]: e.target.value })}
            key={text}
          ></input>
        );
      })}
      <p
        onClick={(e) => {
          navigator.clipboard.writeText(e.target.textContent);
        }}
      >
        {generatedText}
      </p>
      <p className=" text-sm text-gray-400">
        テキストをクリックするとコピーできます。
      </p>
    </>
  );
};

export default function Home() {
  const [generatorType, SetGeneratorType] = useState("translated_book");
  const options = [
    { value: "translated_book", label: "訳本" },
    { value: "general_book", label: "一般書物" },
    { value: "magazine_dissertation", label: "雑誌論文" },
  ];

  return (
    <div className=" font-mono">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl">SoTSoG</h1>
      <Select options={options} onChange={(e) => SetGeneratorType(e.value)} />
      <GenerateComponent method={generatorType} />
    </div>
  );
}
