import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Select from "react-select";
import general_book from "../config/general_book";
import translated_book from "../config/translated_book";
import styles from "../styles/Home.module.css";

const a = { translated_book: translated_book, general_book: general_book };
const GenerateComponent = ({ method }) => {
  const list = a[method].list;
  const inputs = a[method].inputs;
  const [results, setResults] = useState({
    ...inputs,
  });
  const generatedText = a[method].text(results);
  return (
    <>
      {list.map((text) => {
        return (
          <input
            placeholder={text}
            onChange={(e) => setResults({ ...results, [text]: e.target.value })}
            key={text}
          ></input>
        );
      })}
      <p
        onClick={(e) => {
          navigator.clipboard.writeText(e.target.textContent);
        }}
      >
        {generatedText}
      </p>
      <p className=" text-sm text-gray-400">
        テキストをクリックするとコピーできます。
      </p>
    </>
  );
};

export default function Home() {
  const handleChangeType = (e) => {};
  const [generatorType, SetGeneratorType] = useState("translated_book");
  const options = [
    { value: "translated_book", label: "訳本" },
    { value: "general_book", label: "一般書物" },
  ];

  return (
    <div className=" font-mono">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl">SoTSoG</h1>
      <Select options={options} onChange={(e) => SetGeneratorType(e.value)} />
      <GenerateComponent method={generatorType} />
    </div>
  );
}
