import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Select from "react-select";
import complete_book from "../config/complete_book";
import general_book from "../config/general_book";
import magazine_dissertation from "../config/magazine_dissertation";
import translated_book from "../config/translated_book";
import styles from "../styles/Home.module.css";

const format_type = {
  translated_book: translated_book,
  general_book: general_book,
  magazine_dissertation: magazine_dissertation,
  complete_book: complete_book,
};

const GenerateComponent = ({ method }) => {
  const datas = format_type[method].datas;
  const list = Object.keys(datas);
  const [results, setResults] = useState(datas);
  const generatedText = format_type[method].text(results);
  return (
    <>
      <div className="my-5 flex flex-col justify-center">
        {list.map((text) => {
          return (
            <input
              className="my-1 rounded border-2 px-3 py-1"
              placeholder={datas[text]}
              onChange={(e) =>
                setResults({ ...results, [text]: e.target.value })
              }
              key={text}
            ></input>
          );
        })}
      </div>
      <p className="my-10 text-center text-5xl text-gray-500">↓</p>
      <p
        className="cursor-pointer border-2 py-3 text-center active:opacity-60"
        onClick={(e) => {
          navigator.clipboard.writeText(e.target.textContent);
        }}
      >
        {generatedText}
      </p>
      <p className=" my-3 text-center text-xs text-gray-400">
        テキストをクリックするとコピーできます。
      </p>
    </>
  );
};

export default function Home() {
  const [generatorType, SetGeneratorType] = useState("translated_book");
  const options = [
    { value: "translated_book", label: "訳本" },
    { value: "general_book", label: "一般書物" },
    { value: "magazine_dissertation", label: "雑誌論文" },
    { value: "complete_book", label: "全集" },
  ];

  return (
    <div className="font-mon m-auto max-w-5xl p-5">
      <Head>
        <title>SoTSoG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="my-10 text-center text-3xl font-bold">SoTSoG</h1>
      <Select options={options} onChange={(e) => SetGeneratorType(e.value)} />
      <GenerateComponent method={generatorType} />
    </div>
  );
}
